server:
  port: 80

spring:
  application:
    name: sgpo

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

cors:
  originPatterns: http://localhost:5173,http://localhost:3000,https://sgpo-insightlab.vercel.app/

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${TOKEN_EXPIRE_LENGTH}


